#!/bin/sh

# fail fast
set -o errexit
set -o pipefail

git="https://github.com/ddollar/anvil.git"

# save cloud and switch to the standard cloud
cloud=$(heroku cloud)
heroku cloud standard

# release what is on github to anvil-staging
env ANVIL_HOST=https://api.anvilworks.org heroku build $git -r -a anvil-staging

# use the newly-deployed compiler to build itself twice more to
# make sure we have a compiler that can build working apps
env ANVIL_HOST=https://anvil-staging.herokuapp.com heroku build $git -r -a anvil-staging
env ANVIL_HOST=https://anvil-staging.herokuapp.com heroku build $git -r -a anvil-staging

# staging is good, make one more new slug off of it
slug=$(env ANVIL_HOST=https://anvil-staging.herokuapp.com heroku build $git -p)

# release to standard staging and production
heroku release $slug -a anvil-staging
heroku release $slug -a anvil-production

# switch to shadow cloud
heroku cloud shadow

# release to shadow production
heroku release $slug -a anvil-production

# restore old cloud
heroku cloud $cloud
