#!/bin/sh

# fail fast
set -o errexit
set -o pipefail

git="https://github.com/ddollar/anvil.git"

# save cloud and switch to the standard cloud
cloud=$(heroku cloud)
heroku cloud standard

# release to standard staging using standard production
env ANVIL_HOST=https://anvil-production.herokuapp.com heroku build $git -r -a anvil-staging
sleep 2

# build again using staging to make sure it works
slug=$(env ANVIL_HOST=https://anvil-staging.herokuapp.com heroku build $git -p)

# release to standard staging and production
heroku release $slug -a anvil-staging
heroku release $slug -a anvil-production

# switch to shadow cloud
heroku cloud shadow

# release to shadow production
heroku release $slug -a anvil-production

# restore old cloud
heroku cloud $cloud
